[app]
typespeed-app-node ansible_host=51.250.84.81 private_ip=10.10.10.35

[db]
typespeed-db-node ansible_host=89.169.153.158 private_ip=10.10.10.16

[monitoring]
typespeed-monitoring-node ansible_host=51.250.94.37 private_ip=10.10.10.36

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
