[app]
typespeed-app-node ansible_host=93.77.185.146 private_ip=10.10.10.35

[db]
typespeed-db-node ansible_host=93.77.189.161 private_ip=10.10.10.16

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
